name: hive
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  sleek_circular_slider: ^2.0.1
  simple_animations: ^5.0.2
  input_quantity: ^2.1.0
  percent_indicator: ^4.2.3
  flex_color_picker: ^3.3.0
  font_awesome_flutter: ^10.5.0
  flutter_svg: ^2.0.7
  curved_navigation_bar: ^1.0.3
  icons_plus: ^4.0.0
  

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets : 
    - lib/icons/
